### ISSUE TITLE
Two models - one plot

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/auditor#21]
Very nice cheatsheet.
What about the possibility of plotting two models in the same chart. Then it will be easier to compare models.

And/or what about lots inspired by ROC curves or lift curves. In most cases they are used for binary classification, but maybe they can be extended to other glm models as well.

**Comment by agosiewska** [comment]
That is a good idea with the extension of ROC curves.
I have found an article in which the authors attempted to do something like this.
*Hernández-Orallo, J. (2013). ROC curves for regression. Pattern Recognition, 46, 3395-3411.*
I'll look for other approaches and try to adapt and implement some.

**Comment by agosiewska** [comment]
I have added ROC curves and their modifications for regression (RROC, REC).
I also made a draft version of the cheatsheet for them.
https://raw.githubusercontent.com/mi2-warsaw/auditor/master/materials/auditor_cheatsheet_ROC.png

After I complete the documentation of all functions in the auditor, I will add the calculation of AUC and its equivalents for RROC and REC.
