### ISSUE TITLE
List of diagnostic plots with `plot.modelAudit`

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/auditor#23]
Wouldn't it be cool to handle a vector of diagnostics plots by the `plot.modelAudit` function.
I.e. if the `type` argument is longer than a single element then list of plots is returned (more or less like in the plot.lm function)

**Comment by agosiewska** [comment]
Good point. 
Now if length(type)>1 list of plots is returned and they are displayed sequentially like in `plot.lm()`.
