### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by pbiecek** [mi2-warsaw/auditor#25]
Some function names end with `s` some do not
E.g. `plotPrediction` vs `plotResiduals`

**Comment by agosiewska** [comment]
Thank you, I have browsed the names of all functions that generate plots and I'm considering such changes (all in singular form):

| old name            | new name             |
|---------------------|----------------------|
| plotACF             | <-                    |
| plotAutocorrelation |< -                    |
| plotCGains          | plotCumulativeGain   |
| plotCook            | plotCooksDistance    |
| plotHalfNormal      | <-                    |
| plotLift            | <-                    |
| plotModelPCA        | <-                    |
| plotPairs           | plotModelCorrelation |
| plotREC             |< -                    |
| plotResidDens       | plotResidualDensity  |
| plotResiduals       | plotResidual         |
| plotROC             |< -                    |
| plotRROC            | <-                    |
| plotPrediction      |< -                    |
| plotScateLocation   |< -                    |
| plotTwoSidedECDF    | <-                    |
